- name: Set the motd
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    mode: '0644'
- name: Install virtualenv
  ansible.builtin.command: python -m pip install virtualenv

- name: Checkout code from github # noqa: latest
# NB: in folder of provisioning user!
  become: false
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: "{{ project_root }}"
    accept_hostkey: true

- name: Ensures existence /opt/{{ project_root }}
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "/opt/{{ project_root }}"
    - "/opt/{{ project_root }}/paragraphica"
- name: Set credential file
  ansible.builtin.template:
    src: config.ini.j2
    dest: "/opt/{{ project_root }}/config.ini"
    mode: '0700'
  tags: creds
  vars:
    MAPBOX_API: "{{ lookup('community.general.onepassword', 'Mapbox', field='paragraphica', vault='Labs') }}"
    OPENWEATHERMAP_API: "{{ lookup('community.general.onepassword', 'Openweathermap', field='paragraphica', vault='Labs') }}"
    OPENAI_API_KEY: "{{ lookup('community.general.onepassword', 'openai.com', field='paragraphica', vault='Labs') }}"

- name: create virtualenv
  ansible.builtin.command: "virtualenv /opt/{{ project_root }}/.env"
- name: install packages
  ansible.builtin.shell: "/opt/{{ project_root }}/.env/bin/python -m pip install {{ item }}"
  loop:
    - openai
    - streamlit
    - mapbox

- name: Copy role file to working folder
  ansible.builtin.copy:
    src: start_service.sh
    dest: "/opt/{{ project_root }}"
    mode: '0755'
  changed_when: true

- name: Copy main pythons file to working folder
  # this is taken from the checkout repo of provisioning user!
  ansible.builtin.copy:
    src: "{{ project_root }}/{{ item }}"
    dest: "/opt/{{ project_root }}/{{ item }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    remote_src: true
    mode: '0755'
  loop:
    - terra_virtualis.py
  changed_when: true

- name: Copy lib python files to working folder
  # this is taken from the checkout repo of provisioning user!
  ansible.builtin.copy:
    src: "{{ project_root }}/src/{{ item }}"
    dest: "/opt/{{ project_root }}/{{ item }}"
    remote_src: true
    mode: '0755'
  loop:
    - paragraphica/__init__.py
    - paragraphica/api.py
  changed_when: true

- name: Copy startup
  # deliberately placed in the {{ user }} home folder
  ansible.builtin.copy:
    src: start-kiosk.sh
    dest: "/home/{{ user }}/start-kiosk.sh"  
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0755'
  changed_when: true

- name: Setup Terra Virtualis service
  ansible.builtin.template:
    src: gpt.service.j2
    dest: /etc/systemd/system/gpt.service
    owner: root
    group: root
    mode: '0755'
  changed_when: true

- name: Setup Terra Virtualis Viewer service
  ansible.builtin.template:
    src: gpt-viewer.service.j2
    dest: /etc/systemd/system/gpt-viewer.service
    owner: root
    group: root
    mode: '0755'
  changed_when: true
  notify: Enable and restart services